In [6]:
from training_utils import create_siamese_data
from ffcv.writer import DatasetWriter
import numpy as np
import torch
from torch.utils.data import TensorDataset

In [8]:
# Your dataset (`torch.utils.data.Dataset`) of (image, label) pairs
my_dataset = np.ones((100, 128))
dataset = TensorDataset(torch.from_numpy(my_dataset))
dataloader = torch.utils.data.DataLoader(dataset, batch_size=10)
for i, (b) in enumerate(dataloader):
    print(i, b[0].shape)
    break

In [43]:
from ffcv.writer import DatasetWriter
from ffcv.fields import RGBImageField, IntField, FloatField, TorchTensorField

# Your dataset (`torch.utils.data.Dataset`) of (image, label) pairs
mr0 = np.ones((100, 60))
mr1 = np.ones((100, 60))
t = np.ones((100, 1), dtype=int)

dataset_better = TensorDataset(torch.from_numpy(mr0), torch.from_numpy(mr1), torch.from_numpy(t))
dataloader_better = torch.utils.data.DataLoader(dataset_better, batch_size=10)
for i, (m0, m1, t_) in enumerate(dataloader_better):
    print(i, m0.shape, m1.shape, t_.shape)
    break

0 torch.Size([10, 60]) torch.Size([10, 60]) torch.Size([10, 1])


In [44]:
len(dataset_better), dataset_better[0]

(100,
 (tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1.], dtype=torch.float64),
  tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
          1., 1., 1., 1., 1., 1.], dtype=torch.float64),
  tensor([1])))

In [45]:
write_path = "test.beton"
# Pass a type for each data field
writer = DatasetWriter(write_path, {
    # Tune options to optimize dataset size, throughput at train-time
    'mr0': TorchTensorField(
        dtype=torch.float64,
        shape=(60, 1),
    ),
    'mr1': TorchTensorField(
        dtype=torch.float64,
        shape=(60, 1),
    ),
    'target': IntField()
})

# Write dataset
writer.from_indexed_dataset(dataset_better)

100%|██████████| 100/100 [00:00<00:00, 996.40it/s]


In [47]:
from ffcv.loader import Loader, OrderOption
from ffcv.transforms import ToTensor, ToDevice
from ffcv.fields.decoders import IntDecoder, NDArrayDecoder

# Data decoding and augmentation
mr_pipeline = [ NDArrayDecoder(), ToTensor()]
target_pipeline = [IntDecoder(), ToTensor()]

# Pipeline for each data field
pipelines = {
    'mr0': mr_pipeline,
    'mr1': mr_pipeline,
    'target': target_pipeline
}

# Replaces PyTorch data loader (`torch.utils.data.Dataloader`)
loader = Loader(write_path, batch_size=8, num_workers=1,
                order=OrderOption.RANDOM, pipelines=pipelines)


In [52]:
for i, (mr0, mr1, t) in enumerate(loader):
    print(mr0.shape, mr1.shape, t.shape)
    break

torch.Size([8, 60, 1]) torch.Size([8, 60, 1]) torch.Size([8, 1])


In [ ]:

write_path = 'test.beton'

# Pass a type for each data field
writer = DatasetWriter(write_path, {
    # Tune options to optimize dataset size, throughput at train-time
    'image': RGBImageField(
        max_resolution=256
    ),
    'label': IntField()
})

# Write dataset
writer.from_indexed_dataset(my_dataset)

In [ ]:
sh_path = "/scratch_local/owl156-462029/NeglectedFreeLunch/data/resnet50_losses_0.npy",
margin=1
arr = create_siamese_data(sh_path, margin)
np.save(args.destiny_path, arr)