In [1]:
import torch
from siamese_dataloader import Siamese_dataset_folder, Siamese_dataloader
from tqdm import tqdm
import numpy as np

xml_path = "../train_xml/"
dataset = Siamese_dataset_folder(
    root=xml_path,
)


In [5]:
def collate_fn(batch):
    batch_size = len(batch)
    selected_record = torch.zeros((batch_size,1,2))
    estimateTime =  torch.zeros((batch_size,1))
    mouse_record =  torch.zeros((batch_size,30,3))
    labels = torch.zeros((batch_size,1))
    for i,x in enumerate(batch):
        selected_record[i] = torch.from_numpy(x[0])
        estimateTime[i] = x[1]
        mouse_record[i] = torch.from_numpy(x[2])
        labels[i] = x[3]
    return (
        selected_record,
        estimateTime,
        mouse_record,
        labels,
    )

In [6]:
loader = Siamese_dataloader(
    dataset=dataset,
    batch_size=8,
    num_workers=32,
    collate_fn=collate_fn
).run()
mouse_record_history = []
loader = tqdm(loader)

/scratch_local/owl156-429256/scratch_env/lib/python3.9/site-packages/torch/utils/data/dataloader.py:558: UserWarning: This DataLoader will create 32 worker processes in total. Our suggested max number of worker in current system is 8, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
  0%|          | 0/159356 [00:00<?, ?it/s]

In [7]:
for i, (batch) in enumerate(loader):
    break
# print(mr.shape, et.shape, mr)

  0%|          | 0/159356 [00:04<?, ?it/s]


In [10]:
selected_record, estimateTime, mouse_record, labels = batch

In [19]:
selected_record[0], estimateTime[0], mouse_record[0]

(tensor([[0.6500, 0.6133]]),
 tensor([570.]),
 tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 1.0000e+02,  0.0000e+00,  0.0000e+00],
         [ 2.0000e+02,  0.0000e+00,  0.0000e+00],
         [ 3.0000e+02,  0.0000e+00,  0.0000e+00],
         [ 4.0000e+02,  0.0000e+00,  0.0000e+00],
         [ 5.0000e+02,  0.0000e+00,  0.0000e+00],
         [ 6.0000e+02, -1.0000e+00, -1.0000e+00],
         [ 7.0000e+02, -1.0000e+00, -1.0000e+00],
         [ 8.0000e+02, -1.0000e+00, -1.0000e+00],
         [ 9.0000e+02, -1.0000e+00, -1.0000e+00],
         [ 1.0000e+03, -1.0000e+00, -1.0000e+00],
         [ 1.1000e+03, -1.0000e+00, -1.0000e+00],
         [ 1.2000e+03, -1.0000e+00, -1.0000e+00],
         [ 1.3000e+03, -1.0000e+00, -1.0000e+00],
         [ 1.4000e+03, -1.0000e+00, -1.0000e+00],
         [ 1.5000e+03, -1.0000e+00, -1.0000e+00],
         [ 1.6000e+03, -1.0000e+00, -1.0000e+00],
         [ 1.7000e+03, -1.0000e+00, -1.0000e+00],
         [ 1.8000e+03, -1.0000e+00, -1.0000e+00],
    

In [ ]:
mouse_records = np.load('data/mouse_record_interpolated.npy')

In [ ]:
mouse_records.shape

(1, 1, 30, 3)

In [32]:
p = np.load('data/mouse_record_interpolated.npy')

In [33]:
p.shape

(1274843, 30, 3)